# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    # Built-in hooks from pre-commit.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
        # Checks whether your Python files contain valid Python syntax by parsing them into an AST (Abstract Syntax Tree).
      - id: check-ast
        # Checks for accidental debugging statements left in your code.
      - id: debug-statements

    # To block secret-containing commits
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

    # Formatting tool by The Python Software Foundation
    # Fixes the appearance/style.
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black

    # Import sorting tool by The Python Code Quality Authority (PyCQA)
    # To organise your Python import statements consistently.
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

    # Linting tool by The Python Code Quality Authority (PyCQA)
    # Finds problems like Unused imports, Naming conventions, Bad coding practices etc.
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
