[project]
name = "pycore"
version = "0.1.0"
description = "This is a simple python project to test core python functionalities."
readme = "README.md"
authors = [
    { name = "Anupam", email = "anupaminit@gmail.com" }
]
requires-python = ">=3.14.6"
dependencies = []

[project.scripts]
pycore = "pycore:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint]
# Ignore these specific rules globally
ignore = ["C408", "UP031", "UP032", "F821", "C408"]

# Ignore specific rules in specific directories/files
[tool.ruff.lint.per-file-ignores]
"scripts/functions/generator.py" = ["UP028"]
