name: Security Checks
on:
  pull_request:
  push:
    branches:
      - main
      - release/*
env:
  GITHUB_REPO: Pycore

jobs:
  security:
    name: Secrets Scan
    runs-on: ubuntu-latest

    steps:
      - name: Environment Setup
        run: |
          # Access GitHub actions expression
          echo "Source Branch: ${{ github.head_ref }}"
          echo "Target Branch: ${{ github.base_ref }}"

          # Access shell variable
          echo "GitHub Repository: $GITHUB_REPO"

      - name: checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
